Video only button
calzoneman/sync pull request #697
Opened 2017-07-19 01:05 UTC by 0NDR

Made a small change adding a Video-Only button, which makes the video player take up the entire browser window.

Because sometimes you just want to watch the stream without the chat, but dont want the window taking up an entire screen.

2017-07-19 01:08 UTC, Xaekai commented
* There is already a full screen button
* You didn't provide a way to restore without refresh

2017-07-19 01:10 UTC, Xaekai commented
![image](https://user-images.githubusercontent.com/594255/28346206-52d24444-6be4-11e7-86ac-83a28d49067c.png)

2017-07-19 01:10 UTC, calzoneman commented
Fullscreen doesn't cover the case where someone may want to have the video windowed but without the chat.

2017-07-19 01:12 UTC, 0NDR commented
>You didn't provide a way to restore without refresh

I was just mimicking the behavior of the "Chat-Only" button from the Layout drop down. I could work on a restore button, but then a restore button should probably also be added to the "Chat-Only" view.

2017-07-19 01:28 UTC, Xaekai commented
>someone may want to have the video windowed but without the chat

I suppose that's true. I withdraw my complaints.

2017-07-19 02:59 UTC, calzoneman requested changes
Have you checked the browser console to check how many errors occur in video only mode?  I'd imagine it would be pretty noisy because the code makes countless assumptions about the state of the DOM (in particular, that all the things being removed in this PR will always be there).

It'd be nice if we could address this to clean it up a bit.  There is a long term goal to make the code more decoupled to allow for different layouts (chat only, video only, pop-out video, etc.), but that's not even reached the planning stages yet.

2017-07-19 02:59 UTC, calzoneman commented on www/js/util.js
> +{
Move brace to previous line for consistency with existing code style

2017-07-19 02:59 UTC, calzoneman commented on www/js/util.js
> +}
Add an extra newline between this function and the next one

2018-09-25 04:27 UTC, calzoneman commented
Closing due to inactivity.  Feel free to rebase on top of the current HEAD and resubmit if you'd like.

2018-09-25 04:27 UTC, closed without merging